### ISSUE TITLE
Bug:  Damage in Viewer does not match damage in game

### ISSUE THREAD

**Issue by clydeplays** [landaire/wows-toolkit#5]
**Describe the bug**
When viewing my (or another player's) damage in the viewer, it is incorrect.  In the WOWS-Toolkit app, it shows 84,082.49 damage, but in game i received over 101k damage.

**To Reproduce**
1. Play a battle.
2. Write down damage number.
3. Open replay in wows-tk
4. Observe mis-match

**Expected behavior**
Battle damage in app should match that in the game. I believe WG has numerous values for damage in the data structure, IIRC, the one for total damage observed in the game is called "absolute damage" - whereas I'm not sure what "observed damage" is limited to.  Maybe that's all I could see be done from my ship's vantage point.

**Screenshots**
![image](https://github.com/user-attachments/assets/fc3bdc95-89ff-4984-8e59-ada5cc0fd02e)

**Game Version**
13.9.0.0

**Replay File**
https://www.dropbox.com/scl/fi/2elxe9gdwehn8d5itwsv7/20241023_205514_PHSC509-Van-Speijk_14_Atlantic.wowsreplay?rlkey=0o8znssxlasa862783nu2zpqr&dl=0

**Comment by landaire** [comment]
Hey Clyde, apologies for taking a while to respond to this. It wasn't very apparent before, but if you hover over the "Observed Damage" column there is some hover text that explains that floods / fires aren't present. For your teammate's damage the numbers are going to be incorrect a lot because your client doesn't receive events for ships that are not in your render distance.

v0.1.19 is being published right now which uses the raw battle results provided by WG's servers and is guaranteed to be accurate unless a patch shifts the data around. The caveat is, however, your client only receives this data and adds it to the reply if you stay in the game until the end.

**Comment by landaire** [comment]
Oh also, if you hover over a player's potential damage it'll give you a breakdown of damage by armament :)

**Comment by clydeplays** [comment]
No worries on the timing @landaire - thanks for responding.  I'll keep an eye out for updates - thanks for this by the way, its a great little with tons of potential.
